name: General
main: net.craftstars.general.General
authors:
  - Celtic Minstrel
  - Plutonium239
  - Nijikokun
version: 3.3
commands:
  playerlist:
    description: Displays all players that are online.
    permission: general.playerlist
    aliases:
      - online
    usage: |
           /<command>
  who:
    permission: general.who
    description: Displays information about a player.
    aliases: [whois, whoami, playerinfo]
    usage: |
           /<command> [player]
  time:
    permission: general.time
    description: Displays or modifies current world time.
    aliases:
    usage: |
           /<command> [<world>] [=|+|-]<time|duration>
           /<command> add|set <time|duration>
  give:
    permission: general.give
    description: Users to give yourself or another player an item.
    aliases:
      - i
      - item
    usage: |
           /<command> item[:data] [amount] [player]
  getpos:
    permission: general.getpos
    description: Displays detailed information about your position.
    aliases:
      - compass
      - where
      - pos
      - coords
    usage: /<command>
  tell:
    permission: general.tell
    description: Sends another player a private message.
    aliases:
      - msg
      - pm
      - whisper
    usage: /<command> <player> <message>
  spawn:
    permission: general.spawn
    description: Teleports you to the spawn location of your current world.
    aliases:
    usage: |
           /<command> [<player>]
           /<command> [<world>] set [<dest>]
           /<command> [<world>] show
  teleport:
    permission: general.teleport
    description: Teleports a/multiple/all player(s) to another players location.
    aliases: [tele]
    usage: /<command> [<who>] <dest>
  summon:
    permission: general.teleport.other
    description: Teleports a player to your location.
    aliases:
      - tphere
      - teleporthere
      - s
    usage: /<command> [player]
  clear:
    permission: general.clear
    description: Clears your inventory.
    aliases: [clean]
    usage: /<command> [player] [pack|armo[u]r|quickbar]
  take:
    permission: general.take
    description: Removes something from your inventory.
    aliases:
    usage: /<command> item[:data] [amount] [player]
  heal:
    permission: general.heal
    description: Restores your health. (Can also reduce it if you give a negative amount.)
    aliases:
    usage: /heal [player] [amount]
  mobspawn:
    permission: general.mobspawn
    description: Spawns a mob.
    aliases: [mob]
    usage: /mobspawn <mob-name>[;<mount>] [<how-many>]
  kit:
    permission: general.kit
    description: Gives you a kit.
    aliases:
    usage: /kit [kit-name]
  general:
    permission: general.admin
    description: Administrates the plugin.
    aliases:
    usage: /general reload|die|motd|help
  away:
    permission: general.away
    description: Sets your away message
    aliases: [afk]
    usage: /<command> [message]
  items:
    permission: general.give.mass
    description: Gives several items all at once
    aliases:
    usage: /<command> <item1> <item2> ...etc