name: General
main: net.craftstars.general.General
authors:
  - Celtic Minstrel
  - Plutonium239
  - Nijikokun
version: 3.4
commands:
  info.playerlist:
    description: Displays all players that are online.
    permission: general.playerlist
    aliases: [playerlist]
    usage: |
           /<command>
  info.who:
    permission: general.who
    description: Displays information about a player.
    aliases: [who, whoami]
    usage: |
           /<command> [player]
  misc.time:
    permission: general.time
    description: Displays or modifies current world time.
    aliases: [time]
    usage: |
           /<command> [<world>] [=|+|-]<time|duration>
           /<command> add|set <time|duration>
  inven.give:
    permission: general.give
    description: Users to give yourself or another player an item.
    aliases: [give, i, item]
    usage: |
           /<command> item[:data] [amount] [player]
  info.getpos:
    permission: general.getpos
    description: Displays detailed information about your position.
    aliases: [getpos, compass, where]
    usage: /<command>
  chat.tell:
    permission: general.tell
    description: Sends another player a private message.
    aliases: [tell]
    usage: /<command> <player> <message>
  teleport.spawn:
    permission: general.spawn
    description: Shows you the spawn location the specified current world.
    aliases: [spawn]
    usage: /<command> [<world>]
  teleport.setspawn:
    permission: general.spawn.set
    description: Sets to the spawn location of your current world (or the specified one).
    aliases: [setspawn]
    usage: /<command> [<dest>]
  teleport.go:
    permission: general.teleport
    description: Teleports a/multiple/all player(s) to another players location.
    aliases: [go]
    usage: /<command> [<who>] <dest>
  teleport.summon:
    permission: general.teleport.other
    description: Teleports a player to your location.
    aliases: [summon]
    usage: /<command> [player]
  inven.clear:
    permission: general.clear
    description: Clears your inventory.
    aliases: [clear]
    usage: /<command> [player] [pack|armo[u]r|quickbar|all]
  inven.take:
    permission: general.take
    description: Removes something from your inventory.
    aliases: [take]
    usage: /<command> item[:data] [amount] [player]
  misc.heal:
    permission: general.heal
    description: Restores your health. (Can also reduce it if you give a negative amount.)
    aliases: [heal, hurt]
    usage: /heal [player] [amount]
  misc.mobspawn:
    permission: general.mobspawn
    description: Spawns a mob.
    aliases: [mobspawn]
    usage: /mobspawn <mob-name>[;<mount>] [<how-many>]
  inven.kit:
    permission: general.kit
    description: Gives you a kit.
    aliases: [kit]
    usage: /kit [kit-name]
  general:
    permission: general.admin
    description: Administrates the plugin.
    aliases: #[help, motd]
    usage: /general reload|die|motd|help
  chat.away:
    permission: general.away
    description: Sets your away message
    aliases: [away]
    usage: /<command> [message]
  inven.items:
    permission: general.give.mass
    description: Gives several items all at once
    aliases: [items]
    usage: /<command> <item1> <item2> ...etc
  misc.weather:
    permission: general.weather
    description: Affects the weather
    aliases: [weather]
    usage: /<command> [<world>] <weather>